# Monte-Carlo Grain - 2D

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
from upxo._sup import dataTypeHandlers as dth
from upxo.ggrowth.mcgs import mcgs


### Lets suimulate a grain structrue

In [2]:
pxt = mcgs(input_dashboard='C:\\Development\\UPXO\\upxo_library\\src\\upxo\\interfaces\\user_inputs\\input_dashboard_profiling_alg202a.xls')
pxt.simulate()
pxt.detect_grains()


C:\Development\UPXO\upxo_library\src\upxo\interfaces\user_inputs
C:\Development\UPXO\upxo_library\src\upxo\interfaces\user_inputs\input_dashboard_profiling_alg202a.xls
Algo_hops details
(('200.0', 100),)
[False]

 Initiating Monte-Carlo simulation
     xmin, xmax, xinc: 0.0, 100.0, 1.0
     ymin, ymax, yinc: 0.0, 100.0, 1.0
     zmin, zmax, zinc: 0.0, 1000.0, 1.0
     No. of states: 5
     Dimensionality: 2
Using ALG-200: SA's SL NL-1 TP1 C2 unweighted Q-Pott's model:
|--------------- MC SIM RUN IN PROGRESS on: ALG200---------------|
GS temporal slice 0 stored
GS temporal slice 1 stored
GS temporal slice 2 stored
GS temporal slice 3 stored
GS temporal slice 4 stored
GS temporal slice 5 stored
GS temporal slice 6 stored
|--------------- MC SIM RUN COMPLETED on: ALG200---------------|
Using scikit-image for grain identification
MC state = 1:  Num grains = 232
MC state = 2:  Num grains = 232
MC state = 3:  Num grains = 199
MC state = 4:  Num grains = 215
MC state = 5:  Num grains = 230
Te

In [3]:
tslice = 5
pxt.gs[tslice].find_neigh()


Extracting neigh list for all grains


 -------------------------
NOTE:  
 	 This gs tslice has'nt been characterised.
NOTE:  
 	 Charecterising to proceed.
Extracting requested GS props across all available states
--------State value: 5 of 5
----------------------------------------
NOTE:  
 	 this gs tslice has now been charactised.
NOTE:  
 	 Proceeding with neighbourhood gid calculations.

 -------------------------


In [4]:
pxt.gs[tslice].neigh_gid[1]

[35, 36, 67]

### Accessing a MCGS2D grain object

1. Access the grain dictionary inside the temporal slice using `pxt.gs[tslice].g`.
2. This has two fields, `s` and `grain`, the latter being the actual grain object and the former being the MC state value which the grainobject belongs to. Key is the grain number. **Note**: This is planned for optimzation by converting the dict into a list of grain objects. `pxt.gs[tslice].s_gid` and `pxt.gs[tslice].gid_s` will be used to store the gid - s mappings instead.

In [5]:
# For example, get grain object with gid=1
gid = 1 
print(pxt.gs[tslice].g[gid]['s'])
pxt.gs[tslice].g[gid]['grain']

1


As you can see, the `print(pxt.gs[tslice].g[gid]['s'])` printed 1, meaning the grain #1 correspomnds to q=1 of MC states 1:Q. The second output is the UPXo grain2D object


#### Lets get all the grains now.

In [6]:
all_grains = [pxt.gs[tslice].g[i]['grain'] for i in pxt.gs[tslice].g.keys()]
all_grains[:4]

#### Access number of pixels in the 1st and 2nd grains

In [7]:
print(f'Total number of pixels in 1st grain: {all_grains[0].npixels}')
print(f'Total number of pixels in 2nd grain: {all_grains[1].npixels}')

Total number of pixels in 1st grain: 48
Total number of pixels in 2nd grain: 22


#### Access number of pixels of all the grains

In [8]:
npixels = np.array([cell.npixels for cell in all_grains], dtype=float)
npixels

array([  48.,   22.,   56.,    2.,  136.,   70.,   10.,  292.,   48.,
          6.,  324.,   42.,    8.,   32.,   26.,    4.,  206.,  394.,
          4.,  336.,   12.,  164.,  166.,   26.,  440.,   18.,  106.,
         38.,   38.,  694.,  124.,   24.,   12.,    2.,    6.,  382.,
         74.,  390.,  254.,    6.,  416.,   76.,  132.,  116.,   22.,
       1102.,    2.,  368.,   48.,  252.,   60.,  124.,  198.,  286.,
        268.,  194.,   96.,  156.,   24.,   14.,   44.,   54.,    6.,
         12.,    6.,   14.,   90.,    2.,  100.,    4.,  864.,   48.,
        966.,  482.,    2.,  124.,   26.,   18.,  744.,  168.,    2.,
         20.,  312.,  362.,  170.,  192.,  128.,   38.,  108.,  178.,
        144.,   78.,  160.,  158.,   76.,    2.,   78.,  732.,   76.,
         94.,   54.,   14.,    4.,   14.,   86.,   18.,   48.,    4.,
          4.,   26.,  328.,    6.,  122.,   16.,   42.,   32.,   12.,
        502.,  154.,  300.,   48.,  112.,   24.,   34.,   44.,   82.,
         34.,   10.,

#### Test equality of two grains (@morphological parameter: npixels)

In [9]:
print(f"all_grains[0] == all_grains[1]: {all_grains[0] == all_grains[1]}")
print(f"all_grains[0] <= all_grains[1]: {all_grains[0] <= all_grains[1]}")
print(f"all_grains[0] != all_grains[1]: {all_grains[0] != all_grains[1]}")

all_grains[0] == all_grains[1]: [False]
all_grains[0] <= all_grains[1]: [False]
all_grains[0] != all_grains[1]: [True]


#### Test equality of a grain against multipkle grains

In [10]:
print(f"all_grains[0] >= all_grains[1:10]: {all_grains[0] >= all_grains[1:10]}")

all_grains[0] >= all_grains[1:10]: [True, False, True, False, False, True, False, True, True]


#### Test equality of amultipkle grains against a single grain

In [11]:
print(f"all_grains[0:10] >= all_grains[1]: {all_grains[0:10] >= all_grains[1]}")

all_grains[0:10] >= all_grains[1]: [True, True, True, False, True, True, False, True, True, False]


In [12]:
gid = 1
grain = all_grains[gid]

In [13]:
[grain.xmax, grain.xmin, grain.ymax, grain.ymin]

[np.int64(3), np.int64(0), np.int64(16), np.int64(13)]

In [14]:
grain.xstruc

'fcc'

In [15]:
grain.bbox

array([[1, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 0]], dtype=uint8)

In [16]:
grain.bbox_ex

array([[0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=uint8)

In [17]:
grain.centroid

(np.float64(14.363636363636363), np.float64(1.3636363636363635))

In [18]:
grain.coords

array([[13.,  0.],
       [14.,  0.],
       [15.,  0.],
       [13.,  1.],
       [14.,  1.],
       [15.,  1.],
       [14.,  2.],
       [15.,  2.],
       [16.,  2.],
       [14.,  3.],
       [15.,  3.]])

In [19]:
grain.loctree

In [20]:
np.array(grain.neigh)

array([36, 37, 69])

In [21]:
np.array(pxt.gs[tslice].neigh_gid[gid+1])

array([36, 37, 69])

In [22]:
dir(grain)

['__att__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '_grain2d__get_item_behaviour',
 '_px_area',
 'bbox',
 'bbox_bounds',
 'bbox_ex',
 'bbox_ex_bounds',
 'blocks',
 'brec',
 'centroid',
 'control_points_mesh',
 'coords',
 'coordtree',
 'ea',
 'eapert',
 'earef',
 'find_misori',
 'gb_zone',
 'gbid',
 'gbind',
 'gbloc',
 'gbsegs',
 'gbsegs_geo',
 'gbsegs_pre',
 'gbvert',
 'gid',
 'gind',
 'grain_core',
 'laths',
 'loc',
 'loctree',
 'make_coordtree',
 'make_loctree',
 'make_prop',
 'mean_ea',
 'neigh',
 'npixels',
 'paps',
 'plot',
 'plotgb',
 'pl

#### Access the Scikit image property generator objct

In [23]:
grain.set_skprop()

In [24]:
grain.skprop

In [25]:
grain.skprop.moments_hu

array([ 1.74305034e-01,  4.52708092e-03,  2.11951267e-04,  3.70237221e-06,
       -2.77623762e-11, -2.04970107e-07,  9.99293796e-11])

In [26]:
print(f'Grain area = {grain.skprop.area}')
print(f'Major axis length = {grain.skprop.axis_major_length}')
print(f'Minor axis length = {grain.skprop.axis_minor_length}')
print(f'Eccentricity = {grain.skprop.eccentricity}')
print(f'Equivalent dia area = {grain.skprop.equivalent_diameter_area}')
print(f'Euler number = {grain.skprop.euler_number}')
print(f'Feret diameter = {grain.skprop.feret_diameter_max}')
print(f'Moments Hu = {grain.skprop.moments_hu}')
print(f'Morphological orientation = {grain.skprop.orientation}')
print(f'Perimeter = {grain.skprop.perimeter}')
print(f'perimeter Crofton = {grain.skprop.perimeter_crofton}')
print(f'Solidity = {grain.skprop.solidity}')

Grain area = 11.0
Major axis length = 4.610834905547121
Minor axis length = 3.0688576741519786
Eccentricity = 0.7463307334734736
Equivalent dia area = 3.742410318509555
Euler number = 1
Feret diameter = 4.47213595499958
Moments Hu = [ 1.74305034e-01  4.52708092e-03  2.11951267e-04  3.70237221e-06
 -2.77623762e-11 -2.04970107e-07  9.99293796e-11]
Morphological orientation = 0.5285951610360737
Perimeter = 10.65685424949238
perimeter Crofton = 12.392149347147338
Solidity = 0.8461538461538461
