# UPXO 2D Point object

## Introduction

This notebook demonstrates the **UPXO 2D Point** module, which provides two core classes for working with 2D points:

- **`Point2d`**: A feature-rich 2D point class with extensive geometric operations, transformations, and interoperability with external libraries (Shapely, GMSH, PyVista).
- **`p2d_leanest`**: A minimal-footprint 2D point class optimized for memory efficiency and performance-critical applications.

**`Point2d`** offers comprehensive functionality including:
- Equality/inequality comparisons with multiple input types (points, lists, tuples, coordinate arrays)
- Distance calculations (squared and Euclidean)
- Geometric operations (translation, rotation, line intersection)
- Spatial queries (nearest neighbors, clustering, point-in-line tests)
- Multi-format export (NumPy arrays, Shapely geometries, mesh formats)

**`p2d_leanest`** provides basic coordinate storage with minimal overhead, suitable for large-scale point collections where memory is constrained.

Both classes support flexible input formats and can interoperate seamlessly, allowing you to choose the appropriate class based on your performance and functionality requirements.

# Demonstrations

### Imports and aliases
Load `Point2d` (feature-rich) and `p2d_leanest` (minimal footprint) so each example can contrast the full and lean variants. We also pull numpy/matplotlib for potential visualization.

In [58]:
from upxo.geoEntities.point2d import Point2d as p2d
from upxo.geoEntities.point2d import p2d_leanest
import numpy as np
import matplotlib.pyplot as plt
from upxo.geoEntities.point2d import Point2d

### Equality via operator
Shows `==` comparisons between `Point2d` and `p2d_leanest`, plus list/tuple inputs, to clarify how the rich and lean classes normalize coordinates.

In [59]:
print(p2d(3, 4) == p2d_leanest(3, 4))
print(p2d(3, 4) == [p2d_leanest(1, 4), p2d_leanest(3, 4)])
print(p2d(3, 4) == p2d(3, 4))
print(p2d(3, 4) == [p2d(1, 2), p2d(3, 4)])
print(p2d(3, 4) == (p2d(1, 4), p2d(3, 4)))

print(p2d(3, 4) == [[1, 2], [3, 4], [5, 6]])
print(p2d(3, 4) == [[3, 4]])
print(p2d(3, 4) == [[3], [4]])

[True]
[False, True]
[True]
[False, True]
[False, True]
[False, True, False]
[True]
[True]


### Equality via `.eq()`
Demonstrates the explicit `eq` helper on `Point2d` to compare against lean points, lists, tuples, and nested coordinate lists—useful when you want method semantics instead of `==`.

In [60]:
print(p2d(3, 4).eq(p2d_leanest(3, 4)))
print(p2d(3, 4).eq([p2d_leanest(1, 4), p2d_leanest(3, 4)]))
print(p2d(3, 4).eq(p2d(3, 4)))
print(p2d(3, 4).eq([p2d(1, 2), p2d(3, 4)]))
print(p2d(3, 4).eq((p2d(1, 4), p2d(3, 4))))
print(p2d(3, 4).eq([[1, 2], [3, 4], [5, 6]]))
print(p2d(3, 4).eq([[3, 4]]))
print(p2d(3, 4).eq([[3], [4]]))

[True]
[False, True]
[True]
[False, True]
[False, True]
[False, True, False]
[True]
[True]


### Fast equality with `point_spec`
Exercises `eq_fast` where `point_spec` controls expected input shape (single point, array, tuple, leanest object, raw coords). Handy when benchmarking large batches of point comparisons.

In [61]:
print(p2d(3,4).eq_fast(p2d(3,4), point_spec=1))
print(p2d(3,4).eq_fast([p2d(1,2), p2d(3,4)], point_spec=2))
print(p2d(3,4).eq_fast((p2d(1,4), p2d(3,4)), point_spec=2))
print(p2d(3,4).eq_fast(p2d_leanest(3,4), point_spec=3))
print(p2d(3,4).eq_fast([p2d_leanest(1,4), p2d_leanest(3, 4)], point_spec=4))
print(p2d(3,4).eq_fast([1,2], point_spec=5))
print(p2d(3,4).eq_fast([[1,2]], point_spec=6))
print(p2d(3,4).eq_fast([[1,2],[3,4],[5,6]], point_spec=7))
print(p2d(3,4).eq_fast([[3],[4],[5]], point_spec=8))


[True]
[False, True]
[False, True]
[True]
[False, True]
[False]
[False]
[False, True, False]
[True]


### Inequality via `!=` and `.ne()`
Covers both operator and method-based inequality checks to see how `Point2d` and `p2d_leanest` treat mismatched coordinates, sequences, and lean vs full objects.

In [62]:
print(Point2d(3, 4) != p2d_leanest(3, 4))
print(Point2d(3, 4) != [p2d_leanest(1, 4), p2d_leanest(3, 4)])
print(Point2d(3, 4) != Point2d(3, 4))
print(Point2d(3, 4) != [Point2d(1, 2), Point2d(3, 4)])
print(Point2d(3, 4) != (Point2d(1, 4), Point2d(3, 4)))
print(Point2d(3, 4) != [[1, 2], [3, 4], [5, 6]])
print(Point2d(3, 4) != [[3, 4]])
print(Point2d(3, 4) != [[3], [4]])

print(Point2d(3, 4).ne(p2d_leanest(3, 4)))
print(Point2d(3, 4).ne([p2d_leanest(1, 4), p2d_leanest(3, 4)]))
print(Point2d(3, 4).ne(Point2d(3, 4)))
print(Point2d(3, 4).ne([Point2d(1, 2), Point2d(3, 4)]))
print(Point2d(3, 4).ne((Point2d(1, 4), Point2d(3, 4))))
print(Point2d(3, 4).ne([[1, 2], [3, 4], [5, 6]]))
print(Point2d(3, 4).ne([[3, 4]]))
print(Point2d(3, 4).ne([[3], [4]]))

[False]
[True, False]
[False]
[True, False]
[True, False]
[True, False, True]
[False]
[False]
[False]
[True, False]
[False]
[True, False]
[True, False]
[True, False, True]
[False]
[False]


### Vector addition and in-place updates
Adds lean/full points and raw coordinate arrays to illustrate `add` with `update`/`throw` flags. Shows how stateful addition works for `Point2d` while maintaining mutability expectations.

In [63]:
A = p2d(10, 12)
P = [p2d_leanest(-10, -12), p2d_leanest(-2, 2)]
print(A.add(P, update=True, throw=True))
print(A)
d = [[10, 11, 12, 13], [12, 13, 14, 15]]
print(A.add(d, update=True, throw=True))

[uxpo-p2d (0,0), uxpo-p2d (8,14)]
uxpo-p2d (10,12)
[uxpo-p2d (20,24), uxpo-p2d (21,25), uxpo-p2d (22,26), uxpo-p2d (23,27)]


### from_intersection_two_lines
Overloaded return.

Use `Point2d.from_intersection_two_lines` to classify line interactions (collinear overlap, disjoint collinear, and proper intersection). Covers both deterministic and ambiguous cases to show returned structures.

In [64]:
from upxo.geoEntities.sline2d import Sline2d
# Example-1: Collinear lines Case 1
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([0.1, 0.1], [1.8, 1.8])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-2: Collinear lines Case 2
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([0.1, 0.1], [0.8, 0.8])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-3: Collinear lines Case 3
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([-0.1, -0.1], [1.8, 1.8])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-4: Collinear lines Case 4
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([1.8, 1.8], [0.1, 0.1])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-5: non-collinear lines Case 5
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([0, 1], [1, 0])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-6: Collinear lines Case 6
# ----------------------------------
la = Sline2d.by_coord([0.1, 0.1], [0.8, 0.8])
lb = Sline2d.by_coord([0, 0], [1, 1])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-7: Non-Collinear lines Case 7a
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([0, 0], [1, 0])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-8: Non-Collinear lines Case 7b
# ----------------------------------
la = Sline2d.by_coord([0, 0], [1, 1])
lb = Sline2d.by_coord([-0,-0], [1, 0])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-9: Collinear lines Case 8
# ----------------------------------
la = Sline2d.by_coord([0,0], [1,1])
lb = Sline2d.by_coord([0,0], [1,1])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-10: Collinear lines Case 9
# ----------------------------------
la = Sline2d.by_coord([0,0], [1,1])
lb = Sline2d.by_coord([0,0], [-1,-1])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

# Example-11: Collinear lines Case 10
# ----------------------------------
la = Sline2d.by_coord([0,0], [1,0])
lb = Sline2d.by_coord([0,1], [1,1])
print(Point2d.from_intersection_two_lines(la, lb, tool='upxo'))

[uxpo-p2d (0.1,0.1), uxpo-p2d (1.0,1.0)]
[uxpo-p2d (0.1,0.1), uxpo-p2d (0.8,0.8)]
[uxpo-p2d (0,0), uxpo-p2d (1,1)]
[uxpo-p2d (0.1,0.1), uxpo-p2d (1.0,1.0)]
[uxpo-p2d (0.5,0.5)]
[uxpo-p2d (0.1,0.1), uxpo-p2d (0.8,0.8)]
[uxpo-p2d (0,0), uxpo-p2d (0.0,0.0)]
[uxpo-p2d (0,0), uxpo-p2d (0.0,0.0)]
[uxpo-p2d (0,0), uxpo-p2d (1,1)]
[uxpo-p2d (0,0)]
[]


### from_line_factor

Illustrates `Point2d.from_line_factor` for sampling along a 2D line using parametric factors (<0, between 0-1, >1). Great for generating intermediate or extrapolated points without manual algebra.

In [65]:
print(Point2d.from_line_factor(Sline2d(-1,-1, 1,1), +0.25))
print(Point2d.from_line_factor(Sline2d(-1,-1, 1,1), -0.25))
print(Point2d.from_line_factor(Sline2d(-1,-1, 1,1), +1.25))

uxpo-p2d (-0.5,-0.5)
uxpo-p2d (-1.5,-1.5)
uxpo-p2d (1.5,1.5)


### shapely

Access the `shapely` proxy on `Point2d` to integrate with Shapely geometries. Shows attribute access to the underlying Shapely point plus direct coordinate reads.

In [66]:
from upxo.geoEntities.point2d import Point2d
A = Point2d(1.125, 0.456)
A.shapely
A.x, A.y

(1.125, 0.456)

### inside_line

Tests `Point2d.inside_line` with/without endpoints to see how tolerance and `consider_ends` affect inclusion for boundary and off-line points.

In [67]:
print(Point2d(-0.5,-0.5).inside_line(Sline2d.by_coord([0, 0], [1, 1])))
print(Point2d(0.5,0.5).inside_line(Sline2d.by_coord([0, 0], [1, 1])))
print(Point2d(0,0).inside_line(Sline2d.by_coord([0, 0], [1, 1]), consider_ends=False))
print(Point2d(0,0).inside_line(Sline2d.by_coord([0, 0], [1, 1]), consider_ends=True))

False
True
False
True


### squared_distance

Compute squared Euclidean distances from a base `Point2d` to lean points, full points, lists, tuples, and raw coordinate matrices—useful for fast nearest-neighbor prechecks before square roots.

In [68]:
print(Point2d(0, 0).squared_distance(p2d_leanest(3, 4)))
print(Point2d(0, 0).squared_distance([p2d_leanest(1, 4), p2d_leanest(3, 4)]))
print(Point2d(0, 0).squared_distance(Point2d(3, 4)))
print(Point2d(0, 0).squared_distance([Point2d(1, 2), Point2d(3, 4)]))
print(Point2d(0, 0).squared_distance((Point2d(1, 4), Point2d(3, 4))))

print(Point2d(0, 0).squared_distance( [1, 2] ))
print(Point2d(0, 0).squared_distance( [[1, 2]] ))
print(Point2d(0, 0).squared_distance( [[1, 2], [10, 12]] ))
print(Point2d(0, 0).squared_distance( [[1, 2], [10, 12], [0, -5]] ))
print(Point2d(0, 0).squared_distance( [[1, 2, -1, -3], [4, 5, 5, 6]] ))

[25]
[17 25]
[25]
[ 5 25]
[17 25]
[5]
[5]
[  5 244]
[  5 244  25]
[17 29 26 45]


### translate

Explore `translate` with vectors, distances, optional 3D promotion, and `update` control to see when `Point2d` mutates vs returns a new instance.

In [69]:
A = Point2d(0, 0)
print(A.translate(vector=[1, 1], dist=5, update=True, throw=True))

A = Point2d(0, 0)
print(A.translate(vector=[1, 0], dist=5, update=True, throw=True))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1], dist=5, update=True, throw=True))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1], dist=5, update=True, throw=True, make3d=True, zloc=10))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1], dist=5, update=True, throw=True, make3d=False, zloc=10))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1], dist=5, update=False, throw=True, make3d=False, zloc=10))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1, 3], dist=5, update=True, throw=True, make3d=True, zloc=0))

A = Point2d(0, 0)
print(A.translate(vector=[-1, -1, 3], dist=5, update=True, throw=True, make3d=True, zloc=20))

uxpo-p2d (3.5355339059327373,3.5355339059327373)
uxpo-p2d (5.0,0.0)
uxpo-p2d (-3.5355339059327373,-3.5355339059327373)
uxpo-p3d (-3.5355339059327373,-3.5355339059327373,10)
uxpo-p2d (-3.5355339059327373,-3.5355339059327373)
uxpo-p2d (-3.5355339059327373,-3.5355339059327373)
uxpo-p3d (-1.5075567228888183,-1.5075567228888183,4.522670168666455)
uxpo-p3d (-1.5075567228888183,-1.5075567228888183,4.522670168666455)


### translate_to

Use `translate_to` to move a point to another location specified as lean/full objects or raw tuples. Highlights `update` vs copy behavior and how 3D tuples are handled.

In [70]:
A = p2d(0,0)
print(A.translate_to(point=p2d(1,1), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=(p2d(1,1),), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=p2d_leanest(1,1), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=(p2d_leanest(1,1),), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=(1,1), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=((1,1),), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=((1,1,2),), update=True, throw=True))

A = p2d(0,0)
print(A.translate_to(point=((1,1,2),), update=False, throw=False))
print(11111111111111)
A = p2d(0,0)
print(A.translate_to(point=((1,1,2),), update=True, throw=False))
print(A)

uxpo-p2d (1,1)
uxpo-p2d (1,1)
uxpo-p2d (1,1)
uxpo-p2d (1,1)
uxpo-p2d (1,1)
uxpo-p2d (1,1)
uxpo-p3d (1,1,2)
None
11111111111111
None
uxpo-p2d (1,1)


### rotate_about_point
Rotate self point about another point.

Demonstrates rotating a point about another point using degrees, including negative angles and mixed input types (lean, tuple, nested lists). Shows effect of `update`/`throw`.

In [71]:
dut = {'degree': True, 'update': True, 'throw': True}

print(p2d(1, 0).rotate_about_point(p2d(0, 0), -45, **dut))
print(p2d(1, 0).rotate_about_point(p2d(0, 0), +45, **dut))
print(p2d(0, 0).rotate_about_point(p2d(-1, 0), 45, **dut))
print(p2d(0, 0).rotate_about_point(p2d(-1, 0), -45, **dut))
print(p2d(0, 0).rotate_about_point(p2d(-1, 0), 45, **dut))
print(p2d(0.70710678,0.70710678).rotate_about_point(p2d(0, 0), 45, **dut))
print(p2d(0.70710678,0.70710678).rotate_about_point(p2d(0, 0), -45, **dut))
print(p2d(-0.70710678,0.70710678).rotate_about_point(p2d(0, 0), -45, **dut))

print(p2d(1, 0).rotate_about_point((0, 0), 45, **dut))
print(p2d(1, 0).rotate_about_point(([0], [0]), 45, **dut))

print(p2d(0, 0).rotate_about_point(p2d(0, 0), -45, **dut))

uxpo-p2d (0.70710678,-0.70710678)
uxpo-p2d (0.70710678,0.70710678)
uxpo-p2d (-0.29289322,0.70710678)
uxpo-p2d (-0.29289322,-0.70710678)
uxpo-p2d (-0.29289322,0.70710678)
uxpo-p2d (0.0,1.0)
uxpo-p2d (1.0,0.0)
uxpo-p2d (0.0,1.0)
uxpo-p2d (0.70710678,0.70710678)
uxpo-p2d (0.70710678,0.70710678)
uxpo-p2d (0.0,0.0)


### rotate_points
Rotate self point about another point.

Rotates arbitrary input points around a given pivot using `rotate_points`, returning arrays instead of mutating `self`. Includes single points, list-of-pairs, and sign-flipped angles for comparison.

In [72]:
dd = {'degree': True, 'dec': 8}

print(p2d(0, 0).rotate_points(p2d(1, 0), 45, **dd))
print(p2d(1, 0).rotate_points(p2d(0, 0), +45, **dd))
print(p2d(0, 0).rotate_points(p2d(-1, 0), 45, **dd))
print(p2d(0, 0).rotate_points(p2d(-1, 0), -45, **dd))
print(p2d(0, 0).rotate_points(p2d(-1, 0), 45, **dd))
print(p2d(0.70710678, 0.70710678).rotate_points(p2d(0, 0), 45, **dd))
print(p2d(0.70710678, 0.70710678).rotate_points(p2d(0, 0), -45, **dd))
print(p2d(-0.70710678, 0.70710678).rotate_points(p2d(0, 0), -45, **dd))

print(p2d(0, 0).rotate_points((1, 0), 45, **dd))
print(p2d(0, 0).rotate_points(([1], [0]), 45, **dd))
print(p2d(0, 0).rotate_points(([1, 0], [2, 0], [3, 0]), 45, **dd))
print(p2d(0, 0).rotate_points(([1, 0], [2, 0], [3, 0]), -45, **dd))

[[0.70710678 0.70710678]]
[[ 0.29289322 -0.70710678]]
[[-0.70710678 -0.70710678]]
[[-0.70710678  0.70710678]]
[[-0.70710678 -0.70710678]]
[[ 0.70710678 -0.29289322]]
[[-0.29289322  0.70710678]]
[[-0.70710678 -0.29289322]]
[[0.70710678 0.70710678]]
[[0.70710678 0.70710678]]
[[0.70710678 0.70710678]
 [1.41421356 1.41421356]
 [2.12132034 2.12132034]]
[[ 0.70710678 -0.70710678]
 [ 1.41421356 -1.41421356]
 [ 2.12132034 -2.12132034]]


### find_closest_points

Finds indices of nearest neighbors with `find_closest_points`, demonstrating how duplicates are handled when the origin point matches multiple entries.

In [73]:
p2d(0, 0).find_closest_points( [p2d(0, 0), p2d(0, 1), p2d(0, 0)])
# Expected >> array([0, 2], dtype=int64)

array([0, 2])

### find_neigh_points_by_distance

Uses `find_neigh_points_by_distance` to return neighbors within a radius, showcasing list input acceptance and how it returns filtered coordinates.

In [74]:
p2d(0, 0).find_neigh_points_by_distance( [[1, 2], [10, 12], [0, -5]] )

array(0)

### find_neigh_points_by_count

Applies `find_neigh_points_by_count` to fetch the k-nearest neighbors from mixed coordinate inputs, illustrating stable ordering of closest points.

In [75]:
p2d(0, 0).find_neigh_points_by_count( [[1, 2], [10, 12], [0, -5], [0, 0]], 2)

(array([0, 3]),)

### array_by_clustering
#### Explanation
Make an array of points with self as centroid (approx).
#### Parameters

**n**: number of points to create.
**r**: radius
**distribution**: Specifies the distribution type. Options include:
- urand - Uniform random
- nrand - random uniform
- qrand - quadratic random
- crand - cubic random

**return_type**: Type of the return object. Options include:
- coord_list_2d - [[x0, ..., xn], [y0, ..., yn]]
- coords_2d - [[x0, y0], ..., [xn, yn]]
- upxo_2d - upxo 2D point object
- coord_list_3d - [[x0, ..., xn], [y0, ..., yn], [z0, ..., zn]]
- coords_3d - [[x0, y0, z0], ..., [xn, yn, zn]]
- upxo_3d - upxo 3D point object
- gmsh - GMSH poit object
- pyvista - Py-Vista object
**zloc**: Value of z-coordinate if return type is 3D.

#### Return
LIst of point coordinates.

#### Comments
When random, greater the value of n, nearer would be the self to
the centroid.

Executes `array_by_clustering` to generate synthetic neighborhoods around `Point2d`, swapping return types (raw coords, lean points, shapely, gmsh, pyvista) to compare interoperability paths.

In [76]:
print(p2d(0,0).array_by_clustering(n=10, r=1))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='coords_2d'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='upxo_2d'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='upxo_2d_leanest'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='shapely'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='gmsh'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='pyvista'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='coords_3d'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='coord_list_3d'))
print(p2d(0,0).array_by_clustering(n=10, r=1, return_type='mulpoint2d'))

[[ 0.16700574  0.8577513  -0.77601397 -0.45684308  0.60982641 -0.71768447
   0.73094269  0.35971983 -0.2571486   0.66488979]
 [ 0.25786703 -0.21069933  0.3183947  -0.03398946 -0.26501797 -0.4310536
   0.65840281 -0.90051855 -0.53421398 -0.27276284]]
[[ 0.21702156 -0.67052535]
 [ 0.19479367 -0.38776945]
 [ 0.48689112  0.62434186]
 [-0.59641797 -0.74547521]
 [ 0.1713429  -0.21555714]
 [ 0.36303204  0.42570285]
 [ 0.27949018  0.21402228]
 [-0.53724852 -0.62685982]
 [ 0.92165136  0.05698468]
 [ 0.78940069 -0.52568681]]
[uxpo-p2d (0.5400394231191491,-0.3952525886648872), uxpo-p2d (-0.14920458371562637,0.07427789346702332), uxpo-p2d (-0.4422448237729306,0.3086391124215622), uxpo-p2d (-0.5142325198835707,0.02687896048780276), uxpo-p2d (0.769164788071113,-0.6337574403259755), uxpo-p2d (0.5764868467999494,0.3097957057429239), uxpo-p2d (0.4582941272266398,0.13173961548166813), uxpo-p2d (0.053981319518715896,-0.32697433465853987), uxpo-p2d (0.43871072334446193,0.7196672734669345), uxpo-p2d (0.029